name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: ./.github/workflows/reusable.yml
    with:
      environment-variables:
        SOMETHING: some text
        ELSE: true
        MAKE_MY_DAY: 42
        TEXT_ENCAPSULATED: 'some text'
        TEXT_OTHER: 'something else'
