name: CI Reusable Test

on:
  workflow_call:
    inputs:
      environment-variables:
        required: false
        type: string
    secrets:
      NX_CLOUD_ACCESS_TOKEN:
        required: false
      NX_CLOUD_AUTH_TOKEN:
        required: false
      NX_OTHER:
        required: false

jobs:
  main:
    runs-on: ubuntu-latest
    # The name of the job which will invoke this one is expected to be "Nx Cloud - Main Job", and whatever we call this will be appended
    # to that one after a forward slash, so we keep this one intentionally short to produce "Nx Cloud - Main Job / Run" in the Github UI
    name: Run
    steps:
      - name: Process environment-variables
        uses: actions/github-script@v6
        id: env_vars_config
        env:
          ENV_VARS: ${{ inputs.environment-variables }}
        with:
          script: |
            const { execSync } = require('child_process');

            // trim spaces and escape quotes
            const cleanStr = str => str
              .trim()
              .replaceAll(/'/g, "\'")
              .replaceAll(/"/g, '\\\"');

            const parseStr = str =>
              str === 'true' || str === 'TRUE'
                ? true
                : str === 'false' || str === 'FALSE'
                  ? false
                  : isNaN(str)
                    ? str
                    : parseFloat(str);

            const addWorkflowEnvVar = v => {
              execSync(`echo "${v.name}=${parseStr(v.value)}" >> $GITHUB_ENV`);
            }

            const varsStr = process.env.ENV_VARS || '';
            const vars = varsStr
              .split('\n')
              .map(variable => variable.trim())
              .filter(variable => variable.indexOf('=') > 0)
              .map(variable => ({
                name: cleanStr(variable.split('=')[0]),
                value: cleanStr(variable.slice(variable.indexOf('=') + 1))
              }));

            vars.forEach(addWorkflowEnvVar);
      - name: Read values from env
        shell: bash
        run: |
          echo "ELSE: ${{ env.ELSE }}"
          echo "MAKE_MY_DAY: ${{ env.MAKE_MY_DAY }}"
          echo "TEXT_ENCAPSULATED: ${{ env.TEXT_ENCAPSULATED }}"
          echo "TEXT_OTHER: ${{ env.TEXT_OTHER }}"
          echo "NX ${{ env.NX }}"
          echo "TOKEN ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}"
          echo "OTHER ${{ secrets.NX_OTHER }}"
